- platform: template
  sensors:
    alarm_2_time:
      friendly_name: 'Time'
      value_template: >-
        {{ "%0.02d:%0.02d" | format(states("input_number.alarm_2_hour") | int, states("input_number.alarm_2_minutes") | int) }}