- platform: template
  sensors:
    alarm_1_time:
      friendly_name: 'Time'
      value_template: >-
        {{ "%0.02d:%0.02d" | format(states("input_number.alarm_1_hour") | int, states("input_number.alarm_1_minutes") | int) }}