- platform: template
  sensors:
    living_room_light_level:
      friendly_name: 'Living room light level'
      value_template: '{{state_attr("binary_sensor.living_room_motion_sensor", "lx")}}'
      unit_of_measurement: lux
    hall_light_level:
      friendly_name: 'Hall light level'
      value_template: '{{state_attr("binary_sensor.hall_motion_motion_sensor", "lx")}}'
      unit_of_measurement: lux
    bathroom_light_level:
      friendly_name: 'Bathroom light level'
      value_template: '{{state_attr("binary_sensor.bathroom_motion_motion_sensor", "lx")}}'
      unit_of_measurement: lux
    shield_app:
      friendly_name: 'NVidia Shield App id'
      value_template: '{{state_attr("media_player.nvidia_shield_2","app_id")}}'