input_number:
    alarm_2_hour:
        name: Hours
        icon: mdi:timer
        initial: 7
        min: 0
        max: 23
        step: 1
    alarm_2_minutes:
        name: Minutes
        icon: mdi:timer
        initial: 30
        min: 0
        max: 59
        step: 1

input_boolean:
    alarm_2_weekday:
        name: Weekdays
        initial: off
        icon: mdi:calendar-blank
    alarm_2_weekend:
        name: Weekends
        initial: on
        icon: mdi:calendar-blank

sensor:
    - platform: template
      sensors:
         alarm_2_time:
              friendly_name: 'Time'
              value_template: >-
                  {{ "%0.02d:%0.02d" | format(states("input_number.alarm_2_hour") | int, states("input_number.alarm_2_minutes") | int) }}

group:
    alarm_2:
        name: Wake Me Up 2
        icon: mdi:alarm
        entities:
            - sensor.alarm_2_time
            - input_number.alarm_2_hour
            - input_number.alarm_2_minutes
            - input_boolean.alarm_2_weekday
            - input_boolean.alarm_2_weekend


#automation:
#    - id: alarm_2_weekdays
#      alias: "Wake me up (week) 2"
#      trigger:
#          - platform: time_pattern
#            minutes: '/1'
#            seconds: 0
#      condition:
#          - condition: state
#            entity_id: input_boolean.alarm_2_weekday
#            state: 'on'
#          - condition: time
#            weekday:
#                - mon
#                - tue
#                - wed
#                - thu
#                - fri
#          - condition: template
#            value_template: >-
#                {{ now().strftime("%H:%M") == states.sensor.alarm_2_time.state }}
#      action:
#          - event: alarm_2_event
#            event_data:
#                name: Alarm 2 Triggered
#                type: Weekdays

#    - id: alarm_2_weekend
#      alias: "Wake me up (weekend) 2"
#      trigger:
#          - platform: time_pattern
#            minutes: '/1'
#            seconds: 0
#      condition:
#          - condition: state
#            entity_id: input_boolean.alarm_2_weekend
#            state: 'on'
#          - condition: time
#            weekday:
#                - sat
#                - sun
#          - condition: template
#            value_template: >-
#                {{ now().strftime("%H:%M") == states.sensor.alarm_2_time.state }}

#      action:
#          event: alarm_2_event
#          event_data:
#              name: Alarm 2 Triggered
#              type: Weekends