- alias: Cube rotate - Volume livingroom home
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028af239
      action_type: rotate
  condition:
  - condition: state
    entity_id: input_boolean.cube_rotate
    state: 'off'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.ht_xt2
      volume_level: '{%if trigger.event.data.action_value | float > 0 %} {{  states.media_player.ht_xt2.attributes.volume_level
        | float + 0.05 }}  {% else %}   {{  states.media_player.ht_xt2.attributes.volume_level
        | float - 0.05 }}  {% endif %}

        '
  id: d871d2571f9e4bfda00276b9e27cf9ba
- id: '1564924254985'
  alias: Cube tap - TV Source
  trigger:
  - event_data:
      action_type: tap_twice
      entity_id: binary_sensor.cube_158d00028af239
    event_type: xiaomi_aqara.cube_action
    platform: event
  action:
  - data:
      entity_id: media_player.ht_xt2
      source: TV
    service: media_player.select_source
  initial_state: 'on'
- alias: Cube rotate - Light livingroom home
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028af239
      action_type: rotate
  condition:
  - condition: state
    entity_id: input_boolean.cube_rotate
    state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      brightness: '{% if trigger.event.data.action_value | float > 0 %}  {{ states.light.living_room.attributes.brightness
        | int + 50 }}  {% else %}  {{ states.light.living_room.attributes.brightness
        | int - 50 }} {% endif %}

        '
  id: 14a55e1271aa4d37bda3724296f4d329
- alias: Cube share - change rotate type
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00028af239
      action_type: shake_air
  action:
  - data:
      entity_id: input_boolean.cube_rotate
    service: input_boolean.toggle
  id: 1c627955c5dd4dc883b24b033de53f8a